src/byro/office/urls.py
from django.urls import include, re_path

from .views import (
    accounts,
    dashboard,
    documents,
    mails,
    members,
    settings,
    transactions,
    upload,
    users,
)

app_name = "office"
urlpatterns = [
    re_path(
        "^settings/initial$",
        settings.InitialSettings.as_view(),
        name="settings.initial",
    ),
    re_path("^settings/log$", settings.LogView.as_view(), name="settings.log"),
    re_path(
        "^settings/about$", settings.AboutByroView.as_view(), name="settings.about"
    ),
    re_path(
        "^settings/registration$",
        settings.RegistrationConfigView.as_view(),
        name="settings.registration",
    ),
    re_path(
        "^settings/users/$", users.UserListView.as_view(), name="settings.users.list"
    ),
    re_path(
        "^settings/users/add$",
        users.UserCreateView.as_view(),
        name="settings.users.add",
    ),
    re_path(
        r"^settings/users/(?P<pk>\d+)/$",
        users.UserDetailView.as_view(),
        name="settings.users.detail",
    ),
    re_path("^settings$", settings.ConfigurationView.as_view(), name="settings.base"),
    re_path("^$", dashboard.DashboardView.as_view(), name="dashboard"),
    re_path(
        r"^members/typeahead$",
        members.MemberListTypeaheadView.as_view(),
        name="members.typeahead",
    ),
    re_path(r"^members/list$", members.MemberListView.as_view(), name="members.list"),
    re_path(
        r"^members/list/export$",
        members.MemberListExportView.as_view(),
        name="members.list.export",
    ),
    re_path(
        r"^members/list/import$",
        members.MemberListImportView.as_view(),
        name="members.list.import",
    ),
    re_path(
        r"^members/list/disclosure$",
        members.MemberDisclosureView.as_view(),
        name="members.disclosure",
    ),
    re_path(
        r"^members/list/balance$",
        members.MemberBalanceView.as_view(),
        name="members.balance",
    ),
    re_path(r"^members/add$", members.MemberCreateView.as_view(), name="members.add"),
    re_path(
        r"^members/view/(?P<pk>\d+)/",
        include(
            [
                re_path("data$", members.MemberDataView.as_view(), name="members.data"),
                re_path(
                    "timeline$",
                    members.MemberTimelineView.as_view(),
                    name="members.timeline",
                ),
                re_path(
                    "finance$",
                    members.MemberFinanceView.as_view(),
                    name="members.finance",
                ),
                re_path(
                    "operations$",
                    members.MemberOperationsView.as_view(),
                    name="members.operations",
                ),
                re_path(
                    "record-disclosure$",
                    members.MemberRecordDisclosureView.as_view(),
                    name="members.record-disclosure",
                ),
                re_path("log$", members.MemberLogView.as_view(), name="members.log"),
                re_path(
                    "mails$", members.MemberMailsView.as_view(), name="members.mails"
                ),
                re_path(
                    "documents$",
                    members.MemberDocumentsView.as_view(),
                    name="members.documents",
                ),
                re_path(
                    "$", members.MemberDashboardView.as_view(), name="members.dashboard"
                ),
            ]
        ),
    ),
    re_path(
        r"^transactions/(?P<pk>\d+)/",
        transactions.TransactionDetailView.as_view(),
        name="finance.transactions.detail",
    ),
    re_path(
        "^upload/list", upload.UploadListView.as_view(), name="finance.uploads.list"
    ),
    re_path(
        r"^upload/process/(?P<pk>\d+)",
        upload.UploadProcessView.as_view(),
        name="finance.uploads.process",
    ),
    re_path(
        r"^upload/match/(?P<pk>\d+)",
        upload.UploadMatchView.as_view(),
        name="finance.uploads.match",
    ),
    re_path("^upload/add", upload.CsvUploadView.as_view(), name="finance.uploads.add"),
    re_path(
        "^documents/add", documents.DocumentUploadView.as_view(), name="documents.add"
    ),
    re_path(
        r"^documents/(?P<pk>\d+)/(?P<filename>[^/]+)",
        documents.DocumentDownloadView.as_view(),
        name="documents.download",
    ),
    re_path(
        r"^documents/(?P<pk>\d+)",
        documents.DocumentDetailView.as_view(),
        name="documents.detail",
    ),
    re_path(
        "^accounts/$", accounts.AccountListView.as_view(), name="finance.accounts.list"
    ),
    re_path(
        "^accounts/add$",
        accounts.AccountCreateView.as_view(),
        name="finance.accounts.add",
    ),
    re_path(
        r"^accounts/(?P<pk>\d+)/$",
        accounts.AccountDetailView.as_view(),
        name="finance.accounts.detail",
    ),
    re_path(
        r"^accounts/(?P<pk>\d+)/delete$",
        accounts.AccountDeleteView.as_view(),
        name="finance.accounts.delete",
    ),
    re_path(
        "^mails/(?P<pk>[0-9]+)$", mails.MailDetail.as_view(), name="mails.mail.view"
    ),
    re_path(
        "^mails/(?P<pk>[0-9]+)/copy$", mails.MailCopy.as_view(), name="mails.mail.copy"
    ),
    re_path(
        "^mails/(?P<pk>[0-9]+)/delete$",
        mails.OutboxPurge.as_view(),
        name="mails.mail.delete",
    ),
    re_path(
        "^mails/(?P<pk>[0-9]+)/send$",
        mails.OutboxSend.as_view(),
        name="mails.mail.send",
    ),
    re_path("^mails/compose$", mails.Compose.as_view(), name="mails.compose"),
    re_path("^mails/sent$", mails.SentMail.as_view(), name="mails.sent"),
    re_path("^mails/outbox$", mails.OutboxList.as_view(), name="mails.outbox.list"),
    re_path(
        "^mails/outbox/send$", mails.OutboxSend.as_view(), name="mails.outbox.send"
    ),
    re_path(
        "^mails/outbox/purge$", mails.OutboxPurge.as_view(), name="mails.outbox.purge"
    ),
    re_path(
        "^mails/templates$", mails.TemplateList.as_view(), name="mails.templates.list"
    ),
    re_path(
        "^mails/templates/add$",
        mails.TemplateCreate.as_view(),
        name="mails.templates.add",
    ),
    re_path(
        "^mails/templates/(?P<pk>[0-9]+)$",
        mails.TemplateDetail.as_view(),
        name="mails.templates.view",
    ),
    re_path(
        "^templates/(?P<pk>[0-9]+)/delete$",
        mails.TemplateDelete.as_view(),
        name="mails.templates.delete",
    ),
]

src/byro/urls.py
import importlib.util
from contextlib import suppress

from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path

raw_plugin_patterns = []
for app in apps.get_app_configs():
    if hasattr(app, "ByroPluginMeta"):
        if importlib.util.find_spec(app.name + ".urls"):
            urlmod = importlib.import_module(app.name + ".urls")
            single_plugin_patterns = []
            if hasattr(urlmod, "urlpatterns"):
                single_plugin_patterns += urlmod.urlpatterns
            raw_plugin_patterns.append(
                re_path(r"", include((single_plugin_patterns, app.label)))
            )

urlpatterns = [
    re_path(r"", include((raw_plugin_patterns, "plugins"))),
    re_path(r"", include("byro.common.urls", namespace="common")),
    re_path(r"", include("byro.office.urls", namespace="office")),
    re_path(r"^p/", include("byro.public.urls", namespace="public")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    with suppress(ImportError):
        import debug_toolbar

        urlpatterns.insert(0, re_path(r"^__debug__/", include(debug_toolbar.urls)))

src/byro/bookkeeping/models/account.py
from decimal import Decimal

from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.functional import classproperty
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from byro.common.models import LogTargetMixin
from byro.common.models.auditable import Auditable
from byro.common.models.choices import Choices


class AccountCategory(Choices):
    # Categories for double-entry bookkeeping
    ASSET = "asset"  # de: Aktiva, for example your bank account or cash
    LIABILITY = "liability"  # de: Passiva, for example invoices you have to pay
    INCOME = "income"  # de: Ertragskonten, for example for fees paid
    EXPENSE = "expense"  # de: Aufwandskonten, for example for fees to be paid
    EQUITY = "equity"  # de: Eigenkapital, assets less liabilities

    @classproperty
    def choices(cls):
        return (
            (cls.ASSET, _("Asset account")),
            (cls.LIABILITY, _("Liability account")),
            (cls.INCOME, _("Income account")),
            (cls.EXPENSE, _("Expense account")),
            (cls.EQUITY, _("Equity account")),
        )


class AccountTag(models.Model):
    name = models.CharField(max_length=300, null=False, unique=True)
    description = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return self.name


class Account(Auditable, models.Model, LogTargetMixin):
    account_category = models.CharField(
        choices=AccountCategory.choices, max_length=AccountCategory.max_length
    )
    name = models.CharField(max_length=300, null=True)  # e.g. 'Laser donations'
    tags = models.ManyToManyField(AccountTag, related_name="accounts")

    class Meta:
        unique_together = (("account_category", "name"),)

    def __str__(self):
        if self.name:
            return self.name
        return "{self.account_category} account #{self.id}".format(self=self)

    @property
    def bookings(self):
        from byro.bookkeeping.models import Booking

        return Booking.objects.filter(Q(debit_account=self) | Q(credit_account=self))

    @property
    def bookings_with_transaction_data(self):
        from byro.bookkeeping.models import Booking

        return Booking.objects.with_transaction_data().filter(
            Q(debit_account=self) | Q(credit_account=self)
        )

    @property
    def transactions(self):
        from byro.bookkeeping.models import Transaction

        return Transaction.objects.filter(
            Q(bookings__debit_account=self) | Q(bookings__credit_account=self)
        )

    @property
    def unbalanced_transactions(self):
        from byro.bookkeeping.models import Transaction

        return Transaction.objects.unbalanced_transactions().filter(
            Q(bookings__debit_account=self) | Q(bookings__credit_account=self)
        )

    def _filter_by_date(self, qs, start, end):
        if start:
            qs = qs.filter(value_datetime__gte=start)
        if end:
            qs = qs.filter(value_datetime__lte=end)
        return qs

    def balances(self, start=None, end=None):
        end = end or now()
        qs = self._filter_by_date(self.transactions, start, end)

        result = qs.with_balances().aggregate(
            debit=models.functions.Coalesce(
                models.Sum("balances_debit"), 0, output_field=models.DecimalField()
            ),
            credit=models.functions.Coalesce(
                models.Sum("balances_credit"), 0, output_field=models.DecimalField()
            ),
        )

        # ASSET, EXPENSE:  Debit increases balance, credit decreases it
        # INCOME, LIABILITY, EQUITY:  Debit decreases balance, credit increases it

        if self.account_category in (
            AccountCategory.LIABILITY,
            AccountCategory.INCOME,
            AccountCategory.EQUITY,
        ):
            result["net"] = result["credit"] - result["debit"]
        else:
            result["net"] = result["debit"] - result["credit"]

        result = {k: Decimal(v).quantize(Decimal("0.01")) for k, v in result.items()}

        return result

    def get_absolute_url(self):
        return reverse("office:finance.accounts.detail", kwargs={"pk": self.pk})

    def get_object_icon(self):
        return mark_safe('<i class="fa fa-bank"></i> ')

src/byro/office/views/accounts.py
from django import forms
from django.contrib import messages
from django.db import models
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, FormView, ListView

from byro.bookkeeping.models import Account, AccountCategory, Transaction

FORM_CLASS = forms.modelform_factory(Account, fields=["name", "account_category"])

ACCOUNT_COLUMN_HEADERS = {
    # FIXME Check this with an accountant who is a native english speaker
    AccountCategory.INCOME: (_("Charge"), _("Revenue")),
    AccountCategory.ASSET: (_("Increase"), _("Decrease")),
    AccountCategory.EQUITY: (_("Decrease"), _("Increase")),
    AccountCategory.LIABILITY: (_("Decrease"), _("Increase")),
    AccountCategory.EXPENSE: (_("Expense"), _("Rebate")),
}


class AccountListView(ListView):
    template_name = "office/account/list.html"
    context_object_name = "accounts"
    model = Account


class AccountCreateView(FormView):
    template_name = "office/account/add.html"
    model = Account
    form_class = FORM_CLASS

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request,
            _("The account was added, please edit additional details if applicable."),
        )
        self.form = form
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "office:finance.accounts.detail", kwargs={"pk": self.form.instance.pk}
        )


class AccountDetailView(ListView):
    template_name = "office/account/detail.html"
    context_object_name = "bookings"
    model = Transaction
    paginate_by = 25

    def get_object(self):
        if not hasattr(self, "object"):
            self.object = Account.objects.get(pk=self.kwargs["pk"])
        return self.object

    def get_queryset(self):
        qs = self.get_object().bookings_with_transaction_data
        if self.request.GET.get("filter") == "unbalanced":
            qs = qs.exclude(
                transaction_balances_debit=models.F("transaction_balances_credit")
            )
        qs = qs.filter(transaction__value_datetime__lte=now()).order_by(
            "-transaction__value_datetime"
        )
        return qs

    def get_form(self, request=None):
        form = FORM_CLASS(request.POST if request else None, instance=self.get_object())
        form.fields["account_category"].disabled = True
        return form

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["form"] = self.get_form()
        context["account"] = self.get_object()
        context["ACCOUNT_COLUMN_HEADERS"] = ACCOUNT_COLUMN_HEADERS.get(
            self.get_object().account_category, (_("Debit"), _("Credit"))
        )
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form(request)
        if form.is_valid() and form.has_changed():
            form.save()
            messages.success(self.request, _("Your changes have been saved."))
        return redirect(reverse("office:finance.accounts.detail", kwargs=self.kwargs))


class AccountDeleteView(DetailView):
    model = Account
    context_object_name = "account"

src/byro/office/views/dashboard.py
from django.views.generic import TemplateView

from byro.members.models import Member
from byro.members.stats import get_member_statistics


class DashboardView(TemplateView):
    template_name = "office/dashboard.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["member_count"] = Member.objects.all().count()
        context["active_count"] = Member.objects.with_active_membership().count()
        context["stats"] = get_member_statistics()
        return context

src/byro/office/templates/office/account/add.html
{% extends "office/base_headline.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block headline %}{% trans "Add Account …" %}{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <button class="btn btn-success" type="submit">{% trans "Save" %}</button>
    </form>
{% endblock %}

src/byro/office/templates/office/account/base.html
{% extends "office/base_headline.html" %}
{% load i18n %}

{% block headline %}{% if account.name %}{{ account.name }}{% else %}{% trans "Default " %} {{ account.get_account_category_display }}{% endif %}{% endblock %}

{% block content %}
{% block account_content %}
{% endblock %}

{% endblock %}

src/byro/office/templates/office/account/detail.html
{% extends "office/account/base.html" %}
{% load bootstrap4 %}
{% load extract_property %}
{% load i18n %}

{% block account_content %}

<form method='post' class="inline-form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    <button class="btn btn-success" type="submit">{% trans "Save" %}</button>
</form>

<table class="table table-sm">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Purpose" %}<br><i>{% trans "Originator/Recipient" %}</i></th>
            <th>{% trans "Member" %}</th>
            <th>{% trans "Account" %}</th>
            <th class="text-md-right">{{ ACCOUNT_COLUMN_HEADERS.0 }}</th>
            <th class="text-md-right">{{ ACCOUNT_COLUMN_HEADERS.1 }}</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in bookings %}
            {% with transaction=booking.transaction %}
            {% with related_bookings=transaction.cached_bookings %}
                <tr class="transaction-{% if not booking.transaction_balances_debit == booking.transaction_balances_credit %}unbalanced-{% endif %}{% cycle 'row-odd' 'row-even' as account_row %}">
                    <td>
                        <a href="{% url "office:finance.transactions.detail" pk=transaction.pk %}?in_account={{account.pk}}">
                            {% if booking.transaction_balances_debit == booking.transaction_balances_credit %}
                                <span class="fa fa-eye"></span>
                            {% else %}
                                <span class="fa fa-pencil"></span>
                            {% endif %}
                        </a>
                    </td>
                    <td>
                        {% if transaction.documents.count %}
                            <span class="fa fa-paperclip"></span>
                        {% endif %}
                    </td>
                    <td style="white-space: nowrap;">{{ transaction.value_datetime.date }}</td>
                    <td>
                        <a data-toggle="collapse" data-target=".collapse-{{transaction.id}}" aria-controls="collapse-{{transaction.id}}">
                            <span class="fa fa-angle-down"></span>
                            {{ transaction.find_memo }}
                            {% if booking.data.other_party %}
                                <br><i>{{ booking.data.other_party }}</i>
                            {% endif %}
                        </a>
                    </td>
                    <td>{{ booking.member.name }}</td>
                    <td>
                        {% if booking.debit_account %}
                            {{ booking.counter_bookings | extract_property:"credit_account" | join:", <br/> "}}
                        {% elif booking.credit_account %}
                            {{ booking.counter_bookings | extract_property:"debit_account" | join:", <br/> "}}
                        {% endif %}
                    </td>
                    <td class="text-md-right">
                        {% if booking.debit_account %}
                            {{ booking.amount }}
                        {% endif %}
                    </td>
                    <td class="text-md-right">
                        {% if booking.credit_account %}
                            {{ booking.amount }}
                        {% endif %}
                    </td>
                </tr>
                {% for related_booking in related_bookings %}
                <tr class="collapse in related-{{ account_row }}-{% cycle 'related-odd' 'related-even' as related_row %} collapse-{{transaction.id}} {% if forloop.first %}related-first{% endif %} {% if forloop.last %}related-last{% endif %}">
                    <td class="related-empty"></td>
                    <td class="related-empty"></td>
                    <td class="related-empty"></td>
                    <td>
                        {{ related_booking.memo|default:"" }}
                        {% if related_booking.data.other_party %}
                            <br><i>{{ related_booking.data.other_party }}</i>
                        {% endif %}
                    </td>
                    <td>{{ related_booking.member.name }}</td>
                    <td>{{ related_booking.debit_account|default:related_booking.credit_account }}</td>
                    <td class="text-md-right">
                        {% if related_booking.debit_account %}
                            {{ related_booking.amount }}
                        {% endif %}
                    </td>
                    <td class="text-md-right">
                        {% if related_booking.credit_account %}
                            {{ related_booking.amount }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% resetcycle related_row %}
            {% endwith %}
            {% endwith %}
        {% endfor %}
    </tbody>
</table>
{% include "office/pagination.html" %}

{% endblock %}

src/byro/office/templates/office/account/list.html
{% extends "office/base_headline.html" %}

{% load i18n %}

{% block headline %}{% trans "Accounts" %}{% endblock %}

{% block content %}
<p>
<a href="{% url "office:finance.accounts.add" %}" class="btn btn-success">
    <span class="fa fa-plus"></span> {% trans "Add new account" %}
</a>
</p>
<table class="table table-sm">
    <thead>
        <tr>
            {% if pending_transactions %}
            <th class="table-column-small text-md-right">{% trans "Unmatched transactions" %}</th>
            {% endif %}
            <th class="table-column-small">{% trans "Type" %}</th>
            <th>{% trans "Name" %}</th>
            <th class="table-column-small text-md-right">{% trans "Incoming" %}</th>
            <th class="table-column-small text-md-right">{% trans "Outgoing" %}</th>
            <th class="table-column-small text-md-right">{% trans "Balance" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for account in accounts %}
            <tr>
                {% if pending_transactions %}
                    {% with pending_count=account.unbalanced_transactions.count %}
                    {% if pending_count %}
                        <td class="table-warning">
                            <a href="{% url "office:finance.accounts.detail" pk=account.pk %}?filter=unbalanced">
                                {{ pending_count }}
                            </a>
                        </td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    {% endwith %}
                {% endif %}
                <td>{{ account.get_account_category_display }}</td>
                <td><a href="{% url "office:finance.accounts.detail" pk=account.pk %}">
                    {% if account.name %}
                        {{ account.name }}
                    {% else %}
                        {% trans "Default" %}
                        {{ account.get_account_category_display }}
                    {% endif %}
                </a></td>
                {% with balances=account.balances %}
                <td class="text-md-right">{{ balances.debit|default:"" }}</td>
                <td class="text-md-right">{{ balances.credit|default:"" }}</td>
                <td class="text-md-right">{{ balances.net }}</td>
                {% endwith %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% include "office/pagination.html" %}
{% endblock %}